/*
Administrative API

## Overview Manage users, accounts, and account groups in the ThousandEyes platform using the Administrative API.  This API provides the following endpoints that define the operations to manage your organization:     * `/account-groups`: Account groups are used to divide an organization into different sections. These endpoints can be used to create, retrieve, update and delete account groups.   * `/users`: Create, retrieve, update and delete users within an organization.    * `/roles`: Create, retrieve and update roles for the current user.    * `/permissions`: Retrieve all assignable permissions. Used in the context of modifying roles.    * `/audit-user-events`: Retrieve all activity log events.

API version: 7.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thousandeyes

import (
	"encoding/json"
)

// checks if the GetAccountGroups200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAccountGroups200Response{}

// GetAccountGroups200Response struct for GetAccountGroups200Response
type GetAccountGroups200Response struct {
	AccountGroups []AccountGroup `json:"accountGroups,omitempty"`
	Links *SelfLinksLinks `json:"_links,omitempty"`
}

// NewGetAccountGroups200Response instantiates a new GetAccountGroups200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAccountGroups200Response() *GetAccountGroups200Response {
	this := GetAccountGroups200Response{}
	return &this
}

// NewGetAccountGroups200ResponseWithDefaults instantiates a new GetAccountGroups200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAccountGroups200ResponseWithDefaults() *GetAccountGroups200Response {
	this := GetAccountGroups200Response{}
	return &this
}

// GetAccountGroups returns the AccountGroups field value if set, zero value otherwise.
func (o *GetAccountGroups200Response) GetAccountGroups() []AccountGroup {
	if o == nil || IsNil(o.AccountGroups) {
		var ret []AccountGroup
		return ret
	}
	return o.AccountGroups
}

// GetAccountGroupsOk returns a tuple with the AccountGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountGroups200Response) GetAccountGroupsOk() ([]AccountGroup, bool) {
	if o == nil || IsNil(o.AccountGroups) {
		return nil, false
	}
	return o.AccountGroups, true
}

// HasAccountGroups returns a boolean if a field has been set.
func (o *GetAccountGroups200Response) HasAccountGroups() bool {
	if o != nil && !IsNil(o.AccountGroups) {
		return true
	}

	return false
}

// SetAccountGroups gets a reference to the given []AccountGroup and assigns it to the AccountGroups field.
func (o *GetAccountGroups200Response) SetAccountGroups(v []AccountGroup) {
	o.AccountGroups = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetAccountGroups200Response) GetLinks() SelfLinksLinks {
	if o == nil || IsNil(o.Links) {
		var ret SelfLinksLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAccountGroups200Response) GetLinksOk() (*SelfLinksLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetAccountGroups200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given SelfLinksLinks and assigns it to the Links field.
func (o *GetAccountGroups200Response) SetLinks(v SelfLinksLinks) {
	o.Links = &v
}

func (o GetAccountGroups200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAccountGroups200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountGroups) {
		toSerialize["accountGroups"] = o.AccountGroups
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableGetAccountGroups200Response struct {
	value *GetAccountGroups200Response
	isSet bool
}

func (v NullableGetAccountGroups200Response) Get() *GetAccountGroups200Response {
	return v.value
}

func (v *NullableGetAccountGroups200Response) Set(val *GetAccountGroups200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAccountGroups200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAccountGroups200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAccountGroups200Response(val *GetAccountGroups200Response) *NullableGetAccountGroups200Response {
	return &NullableGetAccountGroups200Response{value: val, isSet: true}
}

func (v NullableGetAccountGroups200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAccountGroups200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


