/*
Administrative API

## Overview Manage users, accounts, and account groups in the ThousandEyes platform using the Administrative API.  This API provides the following endpoints that define the operations to manage your organization:     * `/account-groups`: Account groups are used to divide an organization into different sections. These endpoints can be used to create, retrieve, update and delete account groups.   * `/users`: Create, retrieve, update and delete users within an organization.    * `/roles`: Create, retrieve and update roles for the current user.    * `/permissions`: Retrieve all assignable permissions. Used in the context of modifying roles.    * `/audit-user-events`: Retrieve all activity log events.

API version: 7.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thousandeyes

import (
	"encoding/json"
)

// checks if the SelfLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SelfLinks{}

// SelfLinks struct for SelfLinks
type SelfLinks struct {
	Links *SelfLinksLinks `json:"_links,omitempty"`
}

// NewSelfLinks instantiates a new SelfLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSelfLinks() *SelfLinks {
	this := SelfLinks{}
	return &this
}

// NewSelfLinksWithDefaults instantiates a new SelfLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSelfLinksWithDefaults() *SelfLinks {
	this := SelfLinks{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *SelfLinks) GetLinks() SelfLinksLinks {
	if o == nil || IsNil(o.Links) {
		var ret SelfLinksLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SelfLinks) GetLinksOk() (*SelfLinksLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *SelfLinks) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given SelfLinksLinks and assigns it to the Links field.
func (o *SelfLinks) SetLinks(v SelfLinksLinks) {
	o.Links = &v
}

func (o SelfLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SelfLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableSelfLinks struct {
	value *SelfLinks
	isSet bool
}

func (v NullableSelfLinks) Get() *SelfLinks {
	return v.value
}

func (v *NullableSelfLinks) Set(val *SelfLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableSelfLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableSelfLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSelfLinks(val *SelfLinks) *NullableSelfLinks {
	return &NullableSelfLinks{value: val, isSet: true}
}

func (v NullableSelfLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSelfLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


