/*
Administrative API

## Overview Manage users, accounts, and account groups in the ThousandEyes platform using the Administrative API.  This API provides the following endpoints that define the operations to manage your organization:     * `/account-groups`: Account groups are used to divide an organization into different sections. These endpoints can be used to create, retrieve, update and delete account groups.   * `/users`: Create, retrieve, update and delete users within an organization.    * `/roles`: Create, retrieve and update roles for the current user.    * `/permissions`: Retrieve all assignable permissions. Used in the context of modifying roles.    * `/audit-user-events`: Retrieve all activity log events.

API version: 7.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thousandeyes

import (
	"encoding/json"
)

// checks if the GetPermissions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPermissions200Response{}

// GetPermissions200Response struct for GetPermissions200Response
type GetPermissions200Response struct {
	Permissions []Permission `json:"permissions,omitempty"`
	Links *SelfLinksLinks `json:"_links,omitempty"`
}

// NewGetPermissions200Response instantiates a new GetPermissions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPermissions200Response() *GetPermissions200Response {
	this := GetPermissions200Response{}
	return &this
}

// NewGetPermissions200ResponseWithDefaults instantiates a new GetPermissions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPermissions200ResponseWithDefaults() *GetPermissions200Response {
	this := GetPermissions200Response{}
	return &this
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *GetPermissions200Response) GetPermissions() []Permission {
	if o == nil || IsNil(o.Permissions) {
		var ret []Permission
		return ret
	}
	return o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPermissions200Response) GetPermissionsOk() ([]Permission, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *GetPermissions200Response) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given []Permission and assigns it to the Permissions field.
func (o *GetPermissions200Response) SetPermissions(v []Permission) {
	o.Permissions = v
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *GetPermissions200Response) GetLinks() SelfLinksLinks {
	if o == nil || IsNil(o.Links) {
		var ret SelfLinksLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPermissions200Response) GetLinksOk() (*SelfLinksLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *GetPermissions200Response) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given SelfLinksLinks and assigns it to the Links field.
func (o *GetPermissions200Response) SetLinks(v SelfLinksLinks) {
	o.Links = &v
}

func (o GetPermissions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPermissions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.Links) {
		toSerialize["_links"] = o.Links
	}
	return toSerialize, nil
}

type NullableGetPermissions200Response struct {
	value *GetPermissions200Response
	isSet bool
}

func (v NullableGetPermissions200Response) Get() *GetPermissions200Response {
	return v.value
}

func (v *NullableGetPermissions200Response) Set(val *GetPermissions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPermissions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPermissions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPermissions200Response(val *GetPermissions200Response) *NullableGetPermissions200Response {
	return &NullableGetPermissions200Response{value: val, isSet: true}
}

func (v NullableGetPermissions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPermissions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


