/*
Administrative API

## Overview Manage users, accounts, and account groups in the ThousandEyes platform using the Administrative API.  This API provides the following endpoints that define the operations to manage your organization:     * `/account-groups`: Account groups are used to divide an organization into different sections. These endpoints can be used to create, retrieve, update and delete account groups.   * `/users`: Create, retrieve, update and delete users within an organization.    * `/roles`: Create, retrieve and update roles for the current user.    * `/permissions`: Retrieve all assignable permissions. Used in the context of modifying roles.    * `/audit-user-events`: Retrieve all activity log events.

API version: 7.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package thousandeyes

import (
	"encoding/json"
)

// checks if the AccountGroupRoles type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AccountGroupRoles{}

// AccountGroupRoles struct for AccountGroupRoles
type AccountGroupRoles struct {
	AccountGroupRoles []AccountGroupRolesAccountGroupRolesInner `json:"accountGroupRoles,omitempty"`
}

// NewAccountGroupRoles instantiates a new AccountGroupRoles object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAccountGroupRoles() *AccountGroupRoles {
	this := AccountGroupRoles{}
	return &this
}

// NewAccountGroupRolesWithDefaults instantiates a new AccountGroupRoles object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAccountGroupRolesWithDefaults() *AccountGroupRoles {
	this := AccountGroupRoles{}
	return &this
}

// GetAccountGroupRoles returns the AccountGroupRoles field value if set, zero value otherwise.
func (o *AccountGroupRoles) GetAccountGroupRoles() []AccountGroupRolesAccountGroupRolesInner {
	if o == nil || IsNil(o.AccountGroupRoles) {
		var ret []AccountGroupRolesAccountGroupRolesInner
		return ret
	}
	return o.AccountGroupRoles
}

// GetAccountGroupRolesOk returns a tuple with the AccountGroupRoles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AccountGroupRoles) GetAccountGroupRolesOk() ([]AccountGroupRolesAccountGroupRolesInner, bool) {
	if o == nil || IsNil(o.AccountGroupRoles) {
		return nil, false
	}
	return o.AccountGroupRoles, true
}

// HasAccountGroupRoles returns a boolean if a field has been set.
func (o *AccountGroupRoles) HasAccountGroupRoles() bool {
	if o != nil && !IsNil(o.AccountGroupRoles) {
		return true
	}

	return false
}

// SetAccountGroupRoles gets a reference to the given []AccountGroupRolesAccountGroupRolesInner and assigns it to the AccountGroupRoles field.
func (o *AccountGroupRoles) SetAccountGroupRoles(v []AccountGroupRolesAccountGroupRolesInner) {
	o.AccountGroupRoles = v
}

func (o AccountGroupRoles) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AccountGroupRoles) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountGroupRoles) {
		toSerialize["accountGroupRoles"] = o.AccountGroupRoles
	}
	return toSerialize, nil
}

type NullableAccountGroupRoles struct {
	value *AccountGroupRoles
	isSet bool
}

func (v NullableAccountGroupRoles) Get() *AccountGroupRoles {
	return v.value
}

func (v *NullableAccountGroupRoles) Set(val *AccountGroupRoles) {
	v.value = val
	v.isSet = true
}

func (v NullableAccountGroupRoles) IsSet() bool {
	return v.isSet
}

func (v *NullableAccountGroupRoles) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAccountGroupRoles(val *AccountGroupRoles) *NullableAccountGroupRoles {
	return &NullableAccountGroupRoles{value: val, isSet: true}
}

func (v NullableAccountGroupRoles) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAccountGroupRoles) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


